### ISSUE TITLE
One or All prompts?

### ISSUE THREAD

**Issue by XGGNet** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#6]
May I know whether a model corresponds to a specific prompt or whether a model can correspond to all the prompts you have listed at the same time (that means you use massive of all of these prompts in different fashions at the same time to train a single model)?

**Comment by jwyang** [comment]
thanks for the question! We only trained a single model to support all prompts. However, we did not enumerate all the possible prompt combinations during the training, otherwise it will cause a combinatorial explosion. Instead, we use coco data to synthesize the point, box, and scribble queries as the prompts, and in the meanwhile we use coco for training with no-prompt and text prompts. During inference, it can naturally support the combination of multiple types of prompts thanks to our proposed prompting scheme and multi-modal decoder learning pipeline.

**Comment by XGGNet** [comment]
Thank you!
